#!/bin/sh
# Reproducibly build assets/fonts/ (design doc §5.2):
#   Inter 4.1 Regular / Medium / SemiBold (static TTFs, SIL OFL 1.1)
#   Material Symbols Rounded, subset to tools/fonts/icons.txt, variable FILL axis kept
#   (filled = active nav item, outlined = inactive), other axes pinned (wght 400, GRAD 0, opsz 24).
#   Apache License 2.0.
# Also writes assets/fonts/icons.h: icon name -> codepoint constants for the C++ code.
# Needs python3; fontTools is installed into a private venv under build/.
set -eu
ROOT="$(cd "$(dirname "$0")/../.." && pwd)"
OUT="$ROOT/assets/fonts"
WORK="$ROOT/build/fonts"
VENV="$WORK/venv"
INTER_VER=4.1
MSR_BASE="https://raw.githubusercontent.com/google/material-design-icons/master/variablefont"
MSR_NAME='MaterialSymbolsRounded[FILL,GRAD,opsz,wght]'

mkdir -p "$OUT" "$WORK"

if [ ! -x "$VENV/bin/python" ]; then
    python3 -m venv "$VENV"
    "$VENV/bin/pip" install -q "fonttools==4.65.0"
fi
PY="$VENV/bin/python"

# --- Inter ---
if [ ! -f "$WORK/Inter-$INTER_VER.zip" ]; then
    curl -fsSL -o "$WORK/Inter-$INTER_VER.zip" "https://github.com/rsms/inter/releases/download/v$INTER_VER/Inter-$INTER_VER.zip"
fi
rm -rf "$WORK/inter" && mkdir -p "$WORK/inter"
unzip -q -o "$WORK/Inter-$INTER_VER.zip" -d "$WORK/inter"
for w in Regular Medium SemiBold; do
    src="$(find "$WORK/inter" -type f -name "Inter-$w.ttf" | head -1)"
    [ -n "$src" ] || { echo "Inter-$w.ttf not found in release zip" >&2; exit 1; }
    cp "$src" "$OUT/Inter-$w.ttf"
done
cp "$(find "$WORK/inter" -type f -name 'LICENSE.txt' | head -1)" "$OUT/LICENSE-Inter.txt"

# --- Material Symbols Rounded ---
for ext in ttf codepoints; do
    enc="$(printf '%s' "$MSR_NAME" | sed 's/\[/%5B/; s/\]/%5D/')"
    [ -f "$WORK/msr.$ext" ] || curl -fsSL -o "$WORK/msr.$ext" "$MSR_BASE/$enc.$ext"
done
[ -f "$WORK/LICENSE-MaterialSymbols.txt" ] || curl -fsSL -o "$WORK/LICENSE-MaterialSymbols.txt" \
    "https://raw.githubusercontent.com/google/material-design-icons/master/LICENSE"
cp "$WORK/LICENSE-MaterialSymbols.txt" "$OUT/LICENSE-MaterialSymbols.txt"

"$PY" - "$ROOT/tools/fonts/icons.txt" "$WORK/msr.codepoints" "$WORK/msr.ttf" "$OUT" <<'EOF'
import sys
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer
from fontTools import subset

icons_txt, cp_file, ttf, out = sys.argv[1:5]
table = dict(line.split() for line in open(cp_file) if line.strip())
names = [l.strip() for l in open(icons_txt) if l.strip() and not l.startswith("#")]
missing = [n for n in names if n not in table]
if missing:
    sys.exit(f"unknown icon names: {missing}")

font = TTFont(ttf, lazy=False)

# Subset first (fewer glyphs to instance), then pin every axis but FILL.
opts = subset.Options()
opts.layout_features = []          # we address icons by codepoint, not ligature
opts.notdef_outline = True
opts.name_IDs = ["*"]
sub = subset.Subsetter(opts)
sub.populate(unicodes=[int(table[n], 16) for n in names])
sub.subset(font)
font = instancer.instantiateVariableFont(font, {"wght": 400, "GRAD": 0, "opsz": 24})
font.save(f"{out}/MaterialSymbolsRounded.ttf")

with open(f"{out}/icons.h", "w") as h:
    h.write("// Generated by tools/fonts/build_fonts.sh from tools/fonts/icons.txt. Do not edit.\n")
    h.write("#pragma once\n#include <cstdint>\n\nnamespace sumi::icon {\n\n")
    cxx_keywords = {"delete", "new", "default", "export", "register", "class", "private", "public",
                    "switch", "case", "break", "continue", "return", "this", "operator", "template"}
    for n in names:
        ident = n + "_" if n in cxx_keywords else n
        h.write(f"inline constexpr char32_t {ident} = 0x{table[n]};\n")
    h.write("\n} // namespace sumi::icon\n")
print(f"MaterialSymbolsRounded.ttf: {len(names)} icons")
EOF

ls -l "$OUT"
