// Generated by tools/fonts/build_fonts.sh from tools/fonts/icons.txt. Do not edit.
#pragma once
#include <cstdint>

namespace sumi::icon {

inline constexpr char32_t collections_bookmark = 0xe431;
inline constexpr char32_t new_releases = 0xef76;
inline constexpr char32_t history = 0xe8b3;
inline constexpr char32_t explore = 0xe87a;
inline constexpr char32_t more_horiz = 0xe5d3;
inline constexpr char32_t arrow_back = 0xe5c4;
inline constexpr char32_t search = 0xef7a;
inline constexpr char32_t tune = 0xe429;
inline constexpr char32_t more_vert = 0xe5d4;
inline constexpr char32_t close = 0xe5cd;
inline constexpr char32_t refresh = 0xe5d5;
inline constexpr char32_t filter_list = 0xe152;
inline constexpr char32_t sort = 0xe164;
inline constexpr char32_t open_in_new = 0xe89e;
inline constexpr char32_t check = 0xe668;
inline constexpr char32_t check_circle = 0xf0be;
inline constexpr char32_t download = 0xf090;
inline constexpr char32_t download_done = 0xf091;
inline constexpr char32_t error = 0xf8b6;
inline constexpr char32_t chevron_right = 0xe5cc;
inline constexpr char32_t expand_more = 0xe5cf;
inline constexpr char32_t expand_less = 0xe5ce;
inline constexpr char32_t favorite = 0xe87e;
inline constexpr char32_t add = 0xe145;
inline constexpr char32_t delete_ = 0xe92e;
inline constexpr char32_t bookmark = 0xe8e7;
inline constexpr char32_t schedule = 0xefd6;
inline constexpr char32_t sync = 0xe627;
inline constexpr char32_t play_arrow = 0xe037;
inline constexpr char32_t language = 0xea07;
inline constexpr char32_t extension = 0xe87b;
inline constexpr char32_t settings = 0xe8b8;
inline constexpr char32_t info = 0xe88e;
inline constexpr char32_t bar_chart = 0xe26b;
inline constexpr char32_t storage = 0xe1db;
inline constexpr char32_t label = 0xe893;
inline constexpr char32_t backspace = 0xe14a;
inline constexpr char32_t chevron_left = 0xe5cb;
inline constexpr char32_t check_box = 0xe9de;
inline constexpr char32_t check_box_outline_blank = 0xe835;
inline constexpr char32_t download_for_offline = 0xf000;
inline constexpr char32_t light_mode = 0xe518;

} // namespace sumi::icon
